import Link from 'next/link';
import Form from './Form';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <nav className="flex items-center justify-between border-2 border-b-zinc-700 p-4 mb-10">
          <Link href="" className="border-4 border-zinc-500 p-3 text-xl">
            Home
          </Link>
          <Form />
        </nav>
        {children}
      </body>
    </html>
  );
}
